version: "3"
services:

  worker1:
    image: thereisnospoon/wm-test-worker:0.1.1
    ports:
      - "9551:9551"
    environment:
      - WORKER_PORT=9551

  worker2:
    image: thereisnospoon/wm-test-worker:0.1.1
    ports:
      - "9552:9551"
    environment:
      - WORKER_PORT=9551

  worker3:
    image: thereisnospoon/wm-test-worker:0.1.1
    ports:
      - "9553:9551"
    environment:
      - WORKER_PORT=9551
  worker4:
    image: thereisnospoon/wm-test-worker:0.1.1
    ports:
      - "9554:9551"
    environment:
      - WORKER_PORT=9551
